theme: jekyll-theme-minimal
title: Gustavo Di Domenico
description: Welcome! If you are landing on this page, the chances that we have a work relationship are high. The goal of this page is to be transparent about myself so you can know me faster.
